sh_binary(
    name = "command_wrapper",
    srcs = ["command_wrapper.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "clang_config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)
